# Generated by Django 4.0.6 on 2022-07-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cite',
            field=models.CharField(choices=[('Toshkent', 'Toshkent'), ('Toshkent_v', 'Toshkent_v'), ('Andijon ', 'Andijon'), ('Buxoro', 'Buxoro'), ("Farg'ona", "Farg'ona"), ('Sirdaryo', 'Sirdaryo'), ('Jizzax', 'Jizzax'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ("Qoraqalpog'iston Respublikasi", "Qoraqalpog'iston Respublikasi"), ('Samarqand', 'Samarqand'), ('Surxondaryo', 'Surxondaryo'), ('Xorazm', 'Xorazm'), ('Qashqadaryo', 'Qashqadaryo')], max_length=50),
        ),
    ]
