# Generated by Django 4.0.6 on 2022-07-15 06:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=9, unique=True, validators=[accounts.models.CustomUser.validate_length]),
        ),
    ]
