# Generated by Django 4.0.6 on 2022-07-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_price_alter_weddinghall_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddinghall',
            name='event',
            field=models.ManyToManyField(related_name='wedding_hall', to='service.event'),
        ),
    ]
