# Generated by Django 4.0.6 on 2022-07-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_order_location_wedding_order_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='people_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
