# Generated by Django 4.0.6 on 2022-07-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='people_count',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
