# Generated by Django 4.0.6 on 2022-07-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_service_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookeddates',
            options={'verbose_name_plural': 'Забронированные даты'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Мероприятие'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Заказ'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='weddinghall',
            name='cite',
            field=models.CharField(choices=[('Toshkent', 'Toshkent'), ('Toshkent_v', 'Toshkent_v'), ('Andijon ', 'Andijon'), ('Buxoro', 'Buxoro'), ("Farg'ona", "Farg'ona"), ('Sirdaryo', 'Sirdaryo'), ('Jizzax', 'Jizzax'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ("Qoraqalpog'iston Respublikasi", "Qoraqalpog'iston Respublikasi"), ('Samarqand', 'Samarqand'), ('Surxondaryo', 'Surxondaryo'), ('Xorazm', 'Xorazm'), ('Qashqadaryo', 'Qashqadaryo')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='bookeddates',
            unique_together={('date', 'wedding_hall')},
        ),
    ]
