# Generated by Django 4.0.6 on 2022-07-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_bookeddates_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weddinghall',
            options={'verbose_name_plural': 'Ресторан'},
        ),
    ]
